---
cinder:
  enabled_backends: None
  default_backend: None
  backends: []
  api_workers: 5
  console_scripts:
    - cinder-all
    - cinder-api
    - cinder-backup
    - cinder-manage
    - cinder-rootwrap
    - cinder-rtstool
    - cinder-scheduler
    - cinder-volume
    - cinder-volume-usage-audit
  logs:
  - paths:
      - /var/log/cinder/cinder-api.log
    fields:
      type: openstack
      tags: cinder,cinder-api
  - paths:
      - /var/log/cinder/cinder-manage.log
    fields:
      type: openstack
      tags: cinder,cinder-manage
  - paths:
      - /var/log/cinder/cinder-scheduler.log
    fields:
      type: openstack
      tags: cinder,cinder-scheduler
  - paths:
      - /var/log/upstart/tgt.log
    fields:
      type: openstack
      tags: cinder,tgt
