---
dependencies:
  - role: apt-repos
    repos: 
      - repo: 'deb {{ apt_repos.bbg_openstack.repo }} precise main'
        key_url: '{{ apt_repos.bbg_openstack.key_url }}'
      - repo: 'deb {{ apt_repos.hwraid.repo }} precise main'
        key_url: '{{ apt_repos.hwraid.key_url }}'
      - repo: 'deb {{ apt_repos.sensu.repo }} sensu main'
        key_url: '{{ apt_repos.sensu.key_url }}'
  # CMT: this should really be in a Docker role
  - role: apt-repos
    repos: 
    - repo: 'deb {{ apt_repos.docker.repo }} docker main'
      key_url: '{{ apt_repos.docker.key_url }}'
    when: common.docker.enabled|bool
  - role: monitoring-common
