---
- name: restart neutron services
  restart_if_running: service={{ item }}
  when: restart|default('True')
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-openvswitch-agent
    - neutron-linuxbridge-agent
