---
keystone:
  token_expiration_in_seconds: 86400
  admin_workers: 5
  public_workers: 5
  console_scripts:
    - keystone-manage
    - keystone-all
  logs:
    - paths:
      - /var/log/keystone/keystone-all.log
      fields:
        type: openstack
        tags: keystone,keystone-all
    - paths:
        - /var/log/keystone/keystone-manage.log
      fields:
        type: openstack
        tags: keystone,keystone-manage
