---
- name: install system packages for ironic
  apt: pkg={{ item }} state=installed
  with_items:
    - libmysqlclient-dev

- name: create ironic user
  user: name=ironic
        comment=ironic
        shell=/bin/false
        system=yes
        home=/nonexistent
        createhome=no

- name: create ironic log directory
  file: dest=/var/log/ironic state=directory owner=root group=ironic mode=0770

- name: ironic config
  template: src=etc/ironic/ironic.conf dest=/etc/ironic/ironic.conf mode=0640 owner=root group=ironic

- name: ironic policy config
  template: src=etc/ironic/policy.json dest=/etc/ironic/policy.json mode=0640 owner=root group=ironic

- name: ironic paste config
  template: src=etc/ironic/rootwrap.conf dest=/etc/ironic/rootwrap.conf mode=0640 owner=root group=ironic

- name: ironic rootwrap
  command: rsync -avh {{ ironic.path }}/etc/ironic/rootwrap.d /etc/ironic
