---
- name: restart nova services
  restart_if_present: service={{ item }}
  when: restart|default('True')
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-compute
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
