---
- name: get cinder source repo
  git:  repo={{ openstack.git_mirror }}/cinder.git
        dest=/opt/stack/cinder
        version={{ cinder.rev }}
        update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install cinder
    - cinder rootwrap

- meta: flush_handlers
