---
- name: get glance source repo
  git: repo={{ openstack.git_mirror }}/glance.git
       dest=/opt/stack/glance
       version={{ glance.rev }}
       update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install glance
    - restart glance services

- meta: flush_handlers
