---
- name: WORKAROUND - keystone does not include babel in dependencies
  pip: name=babel

- name: get keystone source repo
  git: repo={{ openstack.git_mirror }}/keystone.git
       dest=/opt/stack/keystone
       version={{ keystone.rev }}
       update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install keystone

- meta: flush_handlers
