---
- name: "python prerequities for {{ project_name }}"
  pip: name={{ item.name }} version={{ item.version }}
  with_items: python_requirements
  when: python_requirements is defined and item.version is defined

- name: "python prerequities for {{ project_name }}"
  pip: name={{ item.name }}
  with_items: python_requirements
  when: python_requirements is defined and item.version is not defined

- name: "get {{ project_name }} source repo"
  git: repo="{{ openstack_source.git_mirror }}/{{ project_name }}.git"
       dest="/opt/stack/{{ project_name }}"
       version="{{ openstack_source.project_rev }}"
       update="{{ openstack_source.git_update }}"
  register: result
  until: result|success
  retries: 3
  delay: 10
  notify:
    - "pip install {{ project_name }}"
    - "ensure project config directory exists"
    - "stat rootwrap.d"
    - "remove rootwrap.d if a directory"
    - "setup {{ project_name }} rootwrap"
    - "restart {{ project_name }} services"

- meta: flush_handlers
