---
- name: get nova source repo
  git: |
    repo={{ openstack.git_mirror }}/nova.git
    dest=/opt/stack/nova
    version={{ nova.rev }}
    update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install nova
    - nova rootwrap
    - restart nova services
- meta: flush_handlers
