---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: openstack-source
    project_name: cinder
    project_rev: "{{ cinder.source.rev }}"
    rootwrap: True
    when: openstack_install_method == 'source'

