---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: openstack-package
    project_name: cinder
    package_alternatives: cinder.console_scripts
    when: openstack_source == 'packages'
