---
- name: check if keystone user exists
  action: shell getent passwd keystone
  register: keystone_user
  failed_when: False
  changed_when: False

- name: keystone user
  user: name=keystone shell=/bin/false createhome=no
  when: keystone_user|success

- name: keystone user
  user: name=keystone comment=keystone shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not keystone_user|success

- name: keystone config dir
  file: dest=/etc/keystone state=directory

- name: keystone log dir
  file: dest=/var/log/keystone state=directory mode=0755 owner=keystone
        group=keystone

- name: install keystone service
  upstart_service: name=keystone user=keystone cmd=/usr/local/bin/keystone-all
                   config_dirs=/etc/keystone

- name: configure keystone
  template: src={{ item }} dest=/etc/keystone/ mode=0644
  with_fileglob: ../templates/etc/keystone/*
  notify:
    - restart keystone services

- name: create keystone PKI dirs
  file: path={{ item }} state=directory owner=keystone group=keystone
        mode=0700
  with_items:
    - /etc/keystone/ssl/certs
    - /etc/keystone/ssl/private

- name: generate keystone PKI certs
  command: keystone-manage pki_setup --keystone-user keystone
           --keystone-group keystone
           creates=/etc/keystone/ssl/private/cakey.pem
  run_once: true
  notify:
    - restart keystone services

- name: slurp keystone certs
  slurp: src={{ item }}
  with_items:
    - /etc/keystone/ssl/certs/ca.pem
    - /etc/keystone/ssl/certs/signing_cert.pem
    - /etc/keystone/ssl/private/cakey.pem
    - /etc/keystone/ssl/private/signing_key.pem
  register: pki_certs
  run_once: true
  no_log: true

- name: write out keystone certs
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: keystone
    group: keystone
    mode: 0700
  with_items: pki_certs.results
  no_log: true
  notify:
    - restart keystone services

- name: sync keystone database
  command: keystone-manage db_sync
  when: database_create.changed or force_sync|default('false')|bool

- meta: flush_handlers

- name: start keystone
  service: name=keystone state=started

- name: permit access to keystone
  ufw: rule=allow to_port={{ item }} proto=tcp
  with_items:
    - 5001
    - 35358

- name: add cron job to clean up expired tokens
  template: src=etc/cron.hourly/drop-expired-keystone-tokens
            dest=/etc/cron.hourly/drop-expired-keystone-tokens
            owner=root group=root mode=0755
  run_once: true

- name: ensure only one token flush cron job
  file: path=/etc/cron.hourly/drop-expired-keystone-tokens
        state=absent
  when: inventory_hostname != play_hosts[0]

- include: monitoring.yml tags=monitoring,common
