---
- name: keystone services
  keystone_service: name={{ item.name }}
                    type={{ item.type }}
                    description='{{ item.description }}'
                    public_url={{ item.public_url }}
                    internal_url={{ item.internal_url }}
                    admin_url={{ item.admin_url }}
                    region=RegionOne
                    auth_url=https://{{ endpoints.main }}:5001/v2.0/
                    tenant_name=admin
                    login_user=admin
                    login_password={{ secrets.admin_password }}
                    insecure={{ client.self_signed_cert|lower }}
  with_items: keystone.services
  when: endpoints[item.name] is defined and endpoints[item.name]
