---
neutron:
  rev: 679246d7280e9fb374f8db0972b21b3653724c42
  api_workers: 3
  agent_down_time: 20
  report_interval: 4
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
  enable_flat_networks: False
  alembic_version: 0.7.0

  logs:
    - paths:
        - /var/log/neutron/neutron-server.log
      fields:
        type: openstack
        tags: neutron,neutron-server
    - paths:
        - /var/log/neutron/neutron-dhcp-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-dhcp-agent
    - paths:
        - /var/log/neutron/neutron-l3-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-l3-agent
    - paths:
        - /var/log/neutron/neutron-metadata-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-metadata-agent
