---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: keystone
    logdata: "{{ keystone.logs }}"
  - role: openstack-package 
    project_name: keystone
    package_alternatives: keystone.console_scripts
    when: openstack_source == 'packages'
