---
- name: lesscpy must be in apache PATH
  pip: name=lesscpy version=0.9j

- name: get horizon source repo
  git: |
    repo={{ openstack.git_mirror}}/horizon.git
    dest=/opt/stack/horizon
    version={{ horizon.rev }}
    update={{ openstack.git_update }}
  notify:
    - setup horizon venv
    - compress horizon assets

- name: add python-memcached to horizon requirements
  lineinfile: dest=/opt/stack/horizon/requirements.txt regexp=^python-memcached line=python-memcached
  notify:
    - setup horizon venv

- name: make sure apache knows about horizon ports
  lineinfile: dest=/etc/apache2/ports.conf line="Listen 8080"
  notify:
    - reload apache

- name: create dashboard virtualhost on precise
  template: |
    src=etc/apache2/sites-available/openstack_dashboard.conf
    dest=/etc/apache2/sites-available/openstack_dashboard
  when: ansible_distribution_version == "12.04"
  notify:
    - reload apache

- name: create dashboard virtualhost on other
  template: |
    src=etc/apache2/sites-available/openstack_dashboard.conf
    dest=/etc/apache2/sites-available/openstack_dashboard.conf
  when: ansible_distribution_version != "12.04"
  notify:
    - reload apache

- name: enable horizon apache site
  apache2_site: state=enabled name=openstack_dashboard
  notify:
    - reload apache

- name: create static asset dirs
  file: |
    dest={{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - /opt/stack/horizon/static
    - /opt/stack/horizon/static/dashboard

- name: dashboard settings
  template: |
    src=opt/stack/horizon/openstack_dashboard/local/local_settings.py
    dest=/opt/stack/horizon/openstack_dashboard/local/local_settings.py
    mode=0644
  notify:
    - reload apache

- name: custom horizon logo
  get_url: url={{ horizon.logo_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo.png mode=0644 force=yes

- name: custom horizon splash logo
  get_url: url={{ horizon.logo_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo-splash.png mode=0644 force=yes

- name: custom horizon favicon
  get_url: url={{ horizon.favicon_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/favicon.ico force=yes

- name: put images and fonts where apache can find them
  file: |
    src=/opt/stack/horizon/openstack_dashboard/static/dashboard/{{ item }}
    dest=/opt/stack/horizon/static/dashboard/{{ item }}
    state=link
    owner=www-data
    group=www-data
  with_items:
    - img
    - fonts

- name: ensure apache is running
  service: name=apache2 state=started

- name: Permit HTTP (redirect to HTTPS for Horizon)
  command: ufw allow 80/tcp

- name: Permit HTTPS (Horizon)
  command: ufw allow 443/tcp
