---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: glance
    logdata: "{{ glance.logs }}"
  - role: openstack-package
    project_name: glance
    package_alternatives: glance.console_scripts
    when: openstack_source == 'packages'
