---
dependencies:
  - role: apt
  - role: monitoring-common
  - role: logging-config
    service: glance
    logdata: "{{ glance.logs }}"
  - role: openstack-source
    project_name: glance
    project_rev: "{{ glance.source.rev }}"
    when: openstack_install_method == 'source'
